export const skills = [
  // Hard Skills
  "Solidity",
  "Tailwind",
  "EtherJS",
  "IPFS",
  "NextJS",
  "JavaScript",
  "Python",
  "Java",
  "C++",
  "C#",
  "HTML",
  "CSS",
  "React",
  "Angular",
  "Vue.js",
  "Node.js",
  "Express.js",
  "Django",
  "Flask",
  "SQL",
  "NoSQL",
  "MongoDB",
  "MySQL",
  "PostgreSQL",
  "Firebase",
  "AWS",
  "Azure",
  "Google Cloud",
  "Docker",
  "Kubernetes",
  "Git",
  "RESTful APIs",
  "GraphQL",
  "TensorFlow",
  "PyTorch",
  "Machine Learning",
  "Data Science",
  "Big Data",
  "Artificial Intelligence",
  "Blockchain",
  "Cybersecurity",
  "DevOps",
  "Microservices",
  "Responsive Web Design",
  "UI/UX Design",
  "Agile Methodologies",
  "Scrum",
  "Kanban",
  "Jira",
  "Continuous Integration/Continuous Deployment (CI/CD)",
  "Linux",
  "Shell Scripting",
  "Algorithms",
  "Data Structures",
  "Object-Oriented Programming (OOP)",
  "Functional Programming",
  "Web Development",
  "Mobile App Development",
  "Game Development",
  "Embedded Systems",
  "AR/VR Development",
  "Networking",
  "Information Security",
  "Parallel Computing",
  "Cloud Computing",
  "Test-Driven Development (TDD)",
  "Behavior-Driven Development (BDD)",
  "User Interface (UI) Testing",
  "User Experience (UX) Testing",
  "Software Development Life Cycle (SDLC)",
  "Version Control",
  "Containerization",
  "Scripting",
  "Debugging",
  "Documentation",
  "Code Review",
  "Performance Optimization",
  "API Integration",
  "Version Control Systems",
  "Data Analysis",
  "Elasticsearch",
  "GraphQL",
  "Ruby on Rails",
  "ASP.NET",
  "Heroku",
  "Serverless Architecture",
  "Socket.IO",
  "Hadoop",
  "Redux",
  "Gatsby",
  "Next.js",
  "Nuxt.js",
  "Webpack",
  "Babel",
  "SASS",
  "Less",
  "TypeScript",
  "Rust",
  "Swift",
  "Kotlin",
  "Assembly Language",
  "R",
  "Julia",
  "MATLAB",
  "Adobe Creative Suite",

  // Soft Skills
  "Communication",
  "Problem-solving",
  "Teamwork",
  "Adaptability",
  "Time Management",
  "Leadership",
  "Creativity",
  "Critical Thinking",
  "Emotional Intelligence",
  "Conflict Resolution",
  "Decision Making",
  "Active Listening",
  "Presentation Skills",
  "Empathy",
  "Attention to Detail",
  "Stress Management",
  "Positive Attitude",
  "Networking",
  "Open-mindedness",
  "Resilience",
  "Patience",
  "Self-Motivation",
  "Flexibility",
  "Curiosity",
  "Negotiation",
  "Analytical Thinking",
  "Collaboration",
  "Cultural Intelligence",
  "Tolerance of Ambiguity",
  "Feedback Acceptance",
  "Time Management",
  "Storytelling",
  "Ethical Thinking",
  "Mentoring",
  "Delegation",
  "Diplomacy",
  "Public Speaking",
  "Self-discipline",
  "Humility",
  "Innovation",
  "Professionalism",
  "Work Ethic",
  "Team Building",
  "Conflict Management",
  "Adaptability",
  "Remote Collaboration",

  // Tools and Platforms
  "Figma",
  "Adobe Creative Suite",
  "Jira",
  "Slack",
  "Microsoft Teams",
  "Trello",
  "Asana",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "Microsoft Office",
  "Google Workspace",
  "Zoom",
  "Webex",
  "Sketch",
  "InVision",
  "Zeplin",
  "Notion",
  "Basecamp",
  "Confluence",
  "Monday.com",
  "Airtable",
  "Salesforce",
  "WordPress",
  "Drupal",
  "Magento",
  "Shopify",
  "SAP",
  "ERP Systems",
  "CRM Systems",
  "Hootsuite",
  "Buffer",
  "Sprout Social",
  "Google Analytics",
  "Adobe Analytics",
  "Tableau",
  "Power BI",
  "AWS Console",
  "Microsoft Azure Portal",
  "Google Cloud Platform Console",
  "Docker Hub",
  "Kubernetes Dashboard",
  "Heroku Dashboard",
];
