// Country code to full name mapping for search functionality
export const COUNTRY_MAPPING: Record<string, string[]> = {
  'AF': ['afghanistan'],
  'AL': ['albania'],
  'DZ': ['algeria'],
  'AS': ['american samoa'],
  'AD': ['andorra'],
  'AO': ['angola'],
  'AI': ['anguilla'],
  'AQ': ['antarctica'],
  'AG': ['antigua and barbuda'],
  'AR': ['argentina'],
  'AM': ['armenia'],
  'AW': ['aruba'],
  'AU': ['australia'],
  'AT': ['austria'],
  'AZ': ['azerbaijan'],
  'BS': ['bahamas'],
  'BH': ['bahrain'],
  'BD': ['bangladesh'],
  'BB': ['barbados'],
  'BY': ['belarus'],
  'BE': ['belgium'],
  'BZ': ['belize'],
  'BJ': ['benin'],
  'BM': ['bermuda'],
  'BT': ['bhutan'],
  'BO': ['bolivia'],
  'BQ': ['bonaire'],
  'BA': ['bosnia and herzegovina'],
  'BW': ['botswana'],
  'BV': ['bouvet island'],
  'BR': ['brazil'],
  'IO': ['british indian ocean territory'],
  'BN': ['brunei'],
  'BG': ['bulgaria'],
  'BF': ['burkina faso'],
  'BI': ['burundi'],
  'CV': ['cabo verde', 'cape verde'],
  'KH': ['cambodia'],
  'CM': ['cameroon'],
  'CA': ['canada'],
  'KY': ['cayman islands'],
  'CF': ['central african republic'],
  'TD': ['chad'],
  'CL': ['chile'],
  'CN': ['china'],
  'CX': ['christmas island'],
  'CC': ['cocos islands'],
  'CO': ['colombia'],
  'KM': ['comoros'],
  'CG': ['congo'],
  'CD': ['democratic republic of the congo'],
  'CK': ['cook islands'],
  'CR': ['costa rica'],
  'CI': ['cote divoire', 'ivory coast'],
  'HR': ['croatia'],
  'CU': ['cuba'],
  'CW': ['curacao'],
  'CY': ['cyprus'],
  'CZ': ['czech republic', 'czechia'],
  'DK': ['denmark'],
  'DJ': ['djibouti'],
  'DM': ['dominica'],
  'DO': ['dominican republic'],
  'EC': ['ecuador'],
  'EG': ['egypt'],
  'SV': ['el salvador'],
  'GQ': ['equatorial guinea'],
  'ER': ['eritrea'],
  'EE': ['estonia'],
  'SZ': ['eswatini', 'swaziland'],
  'ET': ['ethiopia'],
  'FK': ['falkland islands'],
  'FO': ['faroe islands'],
  'FJ': ['fiji'],
  'FI': ['finland'],
  'FR': ['france'],
  'GF': ['french guiana'],
  'PF': ['french polynesia'],
  'TF': ['french southern territories'],
  'GA': ['gabon'],
  'GM': ['gambia'],
  'GE': ['georgia'],
  'DE': ['germany'],
  'GH': ['ghana'],
  'GI': ['gibraltar'],
  'GR': ['greece'],
  'GL': ['greenland'],
  'GD': ['grenada'],
  'GP': ['guadeloupe'],
  'GU': ['guam'],
  'GT': ['guatemala'],
  'GG': ['guernsey'],
  'GN': ['guinea'],
  'GW': ['guinea-bissau'],
  'GY': ['guyana'],
  'HT': ['haiti'],
  'HM': ['heard island and mcdonald islands'],
  'VA': ['holy see', 'vatican'],
  'HN': ['honduras'],
  'HK': ['hong kong'],
  'HU': ['hungary'],
  'IS': ['iceland'],
  'IN': ['india'],
  'ID': ['indonesia'],
  'IR': ['iran'],
  'IQ': ['iraq'],
  'IE': ['ireland'],
  'IM': ['isle of man'],
  'IL': ['israel'],
  'IT': ['italy'],
  'JM': ['jamaica'],
  'JP': ['japan'],
  'JE': ['jersey'],
  'JO': ['jordan'],
  'KZ': ['kazakhstan'],
  'KE': ['kenya'],
  'KI': ['kiribati'],
  'KP': ['north korea'],
  'KR': ['south korea', 'korea'],
  'KW': ['kuwait'],
  'KG': ['kyrgyzstan'],
  'LA': ['laos'],
  'LV': ['latvia'],
  'LB': ['lebanon'],
  'LS': ['lesotho'],
  'LR': ['liberia'],
  'LY': ['libya'],
  'LI': ['liechtenstein'],
  'LT': ['lithuania'],
  'LU': ['luxembourg'],
  'MO': ['macao', 'macau'],
  'MK': ['north macedonia', 'macedonia'],
  'MG': ['madagascar'],
  'MW': ['malawi'],
  'MY': ['malaysia'],
  'MV': ['maldives'],
  'ML': ['mali'],
  'MT': ['malta'],
  'MH': ['marshall islands'],
  'MQ': ['martinique'],
  'MR': ['mauritania'],
  'MU': ['mauritius'],
  'YT': ['mayotte'],
  'MX': ['mexico'],
  'FM': ['micronesia'],
  'MD': ['moldova'],
  'MC': ['monaco'],
  'MN': ['mongolia'],
  'ME': ['montenegro'],
  'MS': ['montserrat'],
  'MA': ['morocco'],
  'MZ': ['mozambique'],
  'MM': ['myanmar', 'burma'],
  'NA': ['namibia'],
  'NR': ['nauru'],
  'NP': ['nepal'],
  'NL': ['netherlands'],
  'NC': ['new caledonia'],
  'NZ': ['new zealand'],
  'NI': ['nicaragua'],
  'NE': ['niger'],
  'NG': ['nigeria'],
  'NU': ['niue'],
  'NF': ['norfolk island'],
  'MP': ['northern mariana islands'],
  'NO': ['norway'],
  'OM': ['oman'],
  'PK': ['pakistan'],
  'PW': ['palau'],
  'PS': ['palestine'],
  'PA': ['panama'],
  'PG': ['papua new guinea'],
  'PY': ['paraguay'],
  'PE': ['peru'],
  'PH': ['philippines'],
  'PN': ['pitcairn'],
  'PL': ['poland'],
  'PT': ['portugal'],
  'PR': ['puerto rico'],
  'QA': ['qatar'],
  'RE': ['reunion'],
  'RO': ['romania'],
  'RU': ['russia'],
  'RW': ['rwanda'],
  'BL': ['saint barthelemy'],
  'SH': ['saint helena'],
  'KN': ['saint kitts and nevis'],
  'LC': ['saint lucia'],
  'MF': ['saint martin'],
  'PM': ['saint pierre and miquelon'],
  'VC': ['saint vincent and the grenadines'],
  'WS': ['samoa'],
  'SM': ['san marino'],
  'ST': ['sao tome and principe'],
  'SA': ['saudi arabia'],
  'SN': ['senegal'],
  'RS': ['serbia'],
  'SC': ['seychelles'],
  'SL': ['sierra leone'],
  'SG': ['singapore'],
  'SX': ['sint maarten'],
  'SK': ['slovakia'],
  'SI': ['slovenia'],
  'SB': ['solomon islands'],
  'SO': ['somalia'],
  'ZA': ['south africa'],
  'GS': ['south georgia and the south sandwich islands'],
  'SS': ['south sudan'],
  'ES': ['spain'],
  'LK': ['sri lanka'],
  'SD': ['sudan'],
  'SR': ['suriname'],
  'SJ': ['svalbard and jan mayen'],
  'SE': ['sweden'],
  'CH': ['switzerland'],
  'SY': ['syria'],
  'TW': ['taiwan'],
  'TJ': ['tajikistan'],
  'TZ': ['tanzania'],
  'TH': ['thailand'],
  'TL': ['timor-leste', 'east timor'],
  'TG': ['togo'],
  'TK': ['tokelau'],
  'TO': ['tonga'],
  'TT': ['trinidad and tobago'],
  'TN': ['tunisia'],
  'TR': ['turkey'],
  'TM': ['turkmenistan'],
  'TC': ['turks and caicos islands'],
  'TV': ['tuvalu'],
  'UG': ['uganda'],
  'UA': ['ukraine'],
  'AE': ['united arab emirates', 'uae'],
  'GB': ['united kingdom', 'uk', 'britain'],
  'US': ['united states', 'usa', 'america'],
  'UM': ['united states minor outlying islands'],
  'UY': ['uruguay'],
  'UZ': ['uzbekistan'],
  'VU': ['vanuatu'],
  'VE': ['venezuela'],
  'VN': ['vietnam'],
  'VG': ['british virgin islands'],
  'VI': ['us virgin islands'],
  'WF': ['wallis and futuna'],
  'EH': ['western sahara'],
  'YE': ['yemen'],
  'ZM': ['zambia'],
  'ZW': ['zimbabwe']
};

/**
 * Get country code from full country name
 * @param countryName - Full country name (e.g., "Bangladesh")
 * @returns Country code (e.g., "BD") or null if not found
 */
export function getCountryCodeFromName(countryName: string): string | null {
  const searchName = countryName.toLowerCase().trim();

  for (const [code, names] of Object.entries(COUNTRY_MAPPING)) {
    if (names.some(name => name === searchName)) {
      return code;
    }
  }

  return null;
}

/**
 * Get all possible search terms for a given country input
 * This includes the original input, mapped country codes, and mapped country names
 * @param input - User input (could be country code or name)
 * @returns Array of search terms to use in database queries
 */
export function getCountrySearchTerms(input: string): string[] {
  const searchTerms = new Set<string>();
  const normalizedInput = input.toLowerCase().trim();

  // Always include the original input
  searchTerms.add(normalizedInput);

  // Check if input is a country code
  const countryCode = normalizedInput.toUpperCase();
  if (COUNTRY_MAPPING[countryCode]) {
    // Add all names for this country code
    COUNTRY_MAPPING[countryCode].forEach(name => searchTerms.add(name));
  }

  // Check if input matches any country name
  const foundCode = getCountryCodeFromName(normalizedInput);
  if (foundCode) {
    // Add the country code
    searchTerms.add(foundCode.toLowerCase());
    // Add all other names for this country
    COUNTRY_MAPPING[foundCode].forEach(name => searchTerms.add(name));
  }

  return Array.from(searchTerms);
}